# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 461, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.AppFeed = QtWidgets.QWidget(self.groupBox)
        self.AppFeed.setGeometry(QtCore.QRect(10, 20, 445, 445))
        self.AppFeed.setObjectName("AppFeed")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(10, 10, 120, 61))
        self.startButton.setObjectName("startButton")
        self.TrackRobotButton = QtWidgets.QPushButton(self.centralwidget)
        self.TrackRobotButton.setGeometry(QtCore.QRect(170, 10, 120, 61))
        self.TrackRobotButton.setObjectName("TrackRobotButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(1470, 10, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 80, 461, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.AppFeedAlt = QtWidgets.QWidget(self.groupBox_2)
        self.AppFeedAlt.setGeometry(QtCore.QRect(10, 20, 445, 445))
        self.AppFeedAlt.setObjectName("AppFeedAlt")
        self.ToggleAltButton = QtWidgets.QPushButton(self.centralwidget)
        self.ToggleAltButton.setGeometry(QtCore.QRect(810, 560, 111, 31))
        self.ToggleAltButton.setObjectName("ToggleAltButton")
        self.ProblemDescription = QtWidgets.QTextBrowser(self.centralwidget)
        self.ProblemDescription.setGeometry(QtCore.QRect(960, 100, 401, 271))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ProblemDescription.setFont(font)
        self.ProblemDescription.setFrameShape(QtWidgets.QFrame.Box)
        self.ProblemDescription.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProblemDescription.setLineWidth(3)
        self.ProblemDescription.setObjectName("ProblemDescription")
        self.InputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.InputGroupBox.setGeometry(QtCore.QRect(960, 400, 491, 281))
        self.InputGroupBox.setAutoFillBackground(False)
        self.InputGroupBox.setFlat(False)
        self.InputGroupBox.setObjectName("InputGroupBox")
        self.InputText = QtWidgets.QTextEdit(self.InputGroupBox)
        self.InputText.setGeometry(QtCore.QRect(10, 30, 371, 61))
        self.InputText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputText.setObjectName("InputText")
        self.ImageAlgorithm1 = QtWidgets.QLineEdit(self.InputGroupBox)
        self.ImageAlgorithm1.setGeometry(QtCore.QRect(10, 100, 113, 27))
        self.ImageAlgorithm1.setObjectName("ImageAlgorithm1")
        self.ImageAlgorithm2 = QtWidgets.QLineEdit(self.InputGroupBox)
        self.ImageAlgorithm2.setGeometry(QtCore.QRect(10, 126, 113, 27))
        self.ImageAlgorithm2.setObjectName("ImageAlgorithm2")
        self.ImageAlgorithm3 = QtWidgets.QLineEdit(self.InputGroupBox)
        self.ImageAlgorithm3.setGeometry(QtCore.QRect(10, 152, 113, 27))
        self.ImageAlgorithm3.setObjectName("ImageAlgorithm3")
        self.ImageAlgorithm3_2 = QtWidgets.QLineEdit(self.InputGroupBox)
        self.ImageAlgorithm3_2.setGeometry(QtCore.QRect(10, 178, 113, 27))
        self.ImageAlgorithm3_2.setObjectName("ImageAlgorithm3_2")
        self.ImgAlgSubmitButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.ImgAlgSubmitButton.setGeometry(QtCore.QRect(20, 210, 85, 27))
        self.ImgAlgSubmitButton.setObjectName("ImgAlgSubmitButton")
        self.TextSubmitButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.TextSubmitButton.setGeometry(QtCore.QRect(390, 30, 85, 27))
        self.TextSubmitButton.setObjectName("TextSubmitButton")
        self.ImgAlgResetButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.ImgAlgResetButton.setGeometry(QtCore.QRect(20, 240, 85, 27))
        self.ImgAlgResetButton.setObjectName("ImgAlgResetButton")
        self.checkBox = QtWidgets.QCheckBox(self.InputGroupBox)
        self.checkBox.setGeometry(QtCore.QRect(170, 100, 87, 22))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.InputGroupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(170, 120, 87, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.InputGroupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(170, 140, 87, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.InputGroupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(170, 160, 87, 22))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.InputGroupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(170, 180, 87, 22))
        self.checkBox_5.setObjectName("checkBox_5")
        self.CheckBoxSubmitButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.CheckBoxSubmitButton.setGeometry(QtCore.QRect(170, 210, 85, 27))
        self.CheckBoxSubmitButton.setObjectName("CheckBoxSubmitButton")
        self.CheckBoxResetButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.CheckBoxResetButton.setGeometry(QtCore.QRect(170, 240, 85, 27))
        self.CheckBoxResetButton.setObjectName("CheckBoxResetButton")
        self.radioButton = QtWidgets.QRadioButton(self.InputGroupBox)
        self.radioButton.setGeometry(QtCore.QRect(290, 100, 101, 22))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.InputGroupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(290, 120, 101, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.InputGroupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(290, 140, 101, 22))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.InputGroupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(290, 160, 101, 22))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.InputGroupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(290, 180, 101, 22))
        self.radioButton_5.setObjectName("radioButton_5")
        self.RadialBoxResetButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.RadialBoxResetButton.setGeometry(QtCore.QRect(300, 240, 85, 27))
        self.RadialBoxResetButton.setObjectName("RadialBoxResetButton")
        self.RadialSubmitButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.RadialSubmitButton.setGeometry(QtCore.QRect(300, 210, 85, 27))
        self.RadialSubmitButton.setObjectName("RadialSubmitButton")
        self.ConfidenceBar = QtWidgets.QScrollBar(self.InputGroupBox)
        self.ConfidenceBar.setGeometry(QtCore.QRect(410, 70, 16, 160))
        self.ConfidenceBar.setMaximum(100)
        self.ConfidenceBar.setProperty("value", 50)
        self.ConfidenceBar.setOrientation(QtCore.Qt.Vertical)
        self.ConfidenceBar.setInvertedAppearance(True)
        self.ConfidenceBar.setObjectName("ConfidenceBar")
        self.DifficultyBar = QtWidgets.QScrollBar(self.InputGroupBox)
        self.DifficultyBar.setGeometry(QtCore.QRect(450, 70, 16, 160))
        self.DifficultyBar.setMaximum(100)
        self.DifficultyBar.setProperty("value", 30)
        self.DifficultyBar.setOrientation(QtCore.Qt.Vertical)
        self.DifficultyBar.setInvertedAppearance(True)
        self.DifficultyBar.setObjectName("DifficultyBar")
        self.FormSubmitButton = QtWidgets.QPushButton(self.InputGroupBox)
        self.FormSubmitButton.setGeometry(QtCore.QRect(400, 240, 85, 27))
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.FormSubmitButton.setFont(font)
        self.FormSubmitButton.setObjectName("FormSubmitButton")
        self.label_4 = QtWidgets.QLabel(self.InputGroupBox)
        self.label_4.setGeometry(QtCore.QRect(385, 60, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.InputGroupBox)
        self.label_5.setGeometry(QtCore.QRect(450, 60, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.InputGroupBox)
        self.label_6.setGeometry(QtCore.QRect(434, 200, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.InputGroupBox)
        self.label_7.setGeometry(QtCore.QRect(430, 80, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.HColorSlider = QtWidgets.QSlider(self.centralwidget)
        self.HColorSlider.setGeometry(QtCore.QRect(530, 590, 160, 18))
        self.HColorSlider.setMaximum(180)
        self.HColorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HColorSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.HColorSlider.setTickInterval(20)
        self.HColorSlider.setObjectName("HColorSlider")
        self.SColorSlider = QtWidgets.QSlider(self.centralwidget)
        self.SColorSlider.setGeometry(QtCore.QRect(530, 630, 160, 18))
        self.SColorSlider.setMaximum(360)
        self.SColorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SColorSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SColorSlider.setTickInterval(20)
        self.SColorSlider.setObjectName("SColorSlider")
        self.VColorSlider = QtWidgets.QSlider(self.centralwidget)
        self.VColorSlider.setGeometry(QtCore.QRect(530, 670, 160, 18))
        self.VColorSlider.setMaximum(360)
        self.VColorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.VColorSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.VColorSlider.setTickInterval(20)
        self.VColorSlider.setObjectName("VColorSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 590, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(500, 630, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 670, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(940, 60, 571, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tabWidget.raise_()
        self.groupBox.raise_()
        self.startButton.raise_()
        self.TrackRobotButton.raise_()
        self.progressBar.raise_()
        self.groupBox_2.raise_()
        self.ToggleAltButton.raise_()
        self.ProblemDescription.raise_()
        self.InputGroupBox.raise_()
        self.HColorSlider.raise_()
        self.SColorSlider.raise_()
        self.VColorSlider.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Main Feed"))
        self.startButton.setText(_translate("MainWindow", "Start video"))
        self.TrackRobotButton.setText(_translate("MainWindow", "Find Robot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Alternate"))
        self.ToggleAltButton.setText(_translate("MainWindow", "Toggle Alternate"))
        self.ProblemDescription.setPlaceholderText(_translate("MainWindow", "Problem Description"))
        self.InputGroupBox.setTitle(_translate("MainWindow", "Input"))
        self.InputText.setPlaceholderText(_translate("MainWindow", "User Input"))
        self.ImageAlgorithm1.setPlaceholderText(_translate("MainWindow", "convert color"))
        self.ImageAlgorithm2.setPlaceholderText(_translate("MainWindow", "find in range"))
        self.ImageAlgorithm3.setPlaceholderText(_translate("MainWindow", "erosion"))
        self.ImageAlgorithm3_2.setPlaceholderText(_translate("MainWindow", "dialation"))
        self.ImgAlgSubmitButton.setText(_translate("MainWindow", "Submit"))
        self.TextSubmitButton.setText(_translate("MainWindow", "Submit"))
        self.ImgAlgResetButton.setText(_translate("MainWindow", "Reset"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.CheckBoxSubmitButton.setText(_translate("MainWindow", "Submit"))
        self.CheckBoxResetButton.setText(_translate("MainWindow", "Reset"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_5.setText(_translate("MainWindow", "RadioButton"))
        self.RadialBoxResetButton.setText(_translate("MainWindow", "Reset"))
        self.RadialSubmitButton.setText(_translate("MainWindow", "Submit"))
        self.ConfidenceBar.setToolTip(_translate("MainWindow", "Your confidence level for this problem."))
        self.DifficultyBar.setToolTip(_translate("MainWindow", "the difficulty of this problem"))
        self.FormSubmitButton.setText(_translate("MainWindow", "Submit All"))
        self.label_4.setText(_translate("MainWindow", "confidence"))
        self.label_5.setText(_translate("MainWindow", "difficulty"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "100"))
        self.HColorSlider.setToolTip(_translate("MainWindow", "H color for HSV colorspace"))
        self.SColorSlider.setToolTip(_translate("MainWindow", "S Color for HSV colorspace"))
        self.VColorSlider.setToolTip(_translate("MainWindow", "V Color for HSV colorspace"))
        self.label.setText(_translate("MainWindow", "H"))
        self.label_2.setText(_translate("MainWindow", "S"))
        self.label_3.setText(_translate("MainWindow", "V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 3"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

